input {

  file {

    path => "/usr/share/logstash/sample-data/sample.log"

    start_position => "beginning"

  }

}

output {

  elasticsearch {

    hosts => ["http://elasticsearch:9200"]

    index => "sample-logs"

  }

}

